### ISSUE TITLE
vv8-post-processor "'EventTarget' has no such member name 'performance'

### ISSUE THREAD

**Issue by fhertz** [wspr-ncsu/visiblev8#72] opened 2023-09-20 10:41 UTC
Hello, running the last 115.0.5790.170 , i got this :

./vv8-post-processor -aggs ufeatures vv8*.log
2023/09/20 12:38:32 main.go:185: Output enabled: ufeatures
2023/09/20 12:38:32 main.go:241: Opening vv8-1695205697440-1911143-1911143-chrome.0.log...
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 ufeatures.go:36: Yo!
2023/09/20 12:38:32 main.go:313: interface 'EventTarget' has no such member name 'performance'

**Comment by Ale0x78** [comment] 2024-02-02 15:36
EvenTarget doesn't seem to have any properties or methods named performance
https://developer.mozilla.org/en-US/docs/Web/API/EventTargetw

Could you provide the web pages these were collected from?

**Comment by sohomdatta1** [comment] 2024-06-08 21:31
This is going to be impossible to debug without a log file or a reproducible web page. Closing for now since we have recently made some fixes to the idlapis code.

**Closed by sohomdatta1** 2024-06-08 21:31 UTC
